INSERT INTO EMAIL_CONFIG(EMAIL_CONFIG_ID,HOST,PORT,USER_NAME,PASSWORD,PROTOCOL,SMTP_AUTH,STARTTLS) VALUES (1,'mail.onesevenhome.com','587','info@onesevenhome.com','Info@osh','smtp',1,1);
INSERT INTO EMAIL_CONFIG(EMAIL_CONFIG_ID,HOST,PORT,USER_NAME,PASSWORD,PROTOCOL,SMTP_AUTH,STARTTLS) VALUES (2,'mail.onesevenhome.com','587','sales@onesevenhome.com','Sales@osh','smtp',1,1);
INSERT INTO EMAIL_CONFIG(EMAIL_CONFIG_ID,HOST,PORT,USER_NAME,PASSWORD,PROTOCOL,SMTP_AUTH,STARTTLS) VALUES (3,'mail.onesevenhome.com','587','admin@onesevenhome.com','Admin@osh','smtp',1,1);
INSERT INTO EMAIL_CONFIG(EMAIL_CONFIG_ID,HOST,PORT,USER_NAME,PASSWORD,PROTOCOL,SMTP_AUTH,STARTTLS) VALUES (4,'mail.onesevenhome.com','587','orders@onesevenhome.com','Orders@osh','smtp',1,1);
INSERT INTO EMAIL_CONFIG(EMAIL_CONFIG_ID,HOST,PORT,USER_NAME,PASSWORD,PROTOCOL,SMTP_AUTH,STARTTLS) VALUES (5,'smtp.gmail.com','587','sm19811130@gmail.com','pranav1234','smtp',1,1);
